pod/playlist/urls.py
from django.conf.urls import url
from pod.playlist.views import my_playlists
from pod.playlist.views import playlist_play
from pod.playlist.views import playlist

urlpatterns = [
    url(r"^playlist/edit/$", playlist, name="playlist_edit"),
    url(r"^playlist/edit/(?P<slug>[\-\d\w]+)/$", playlist, name="playlist_edit"),
    url(r"^playlist/(?P<slug>[\-\d\w]+)/$", playlist_play, name="playlist"),
    url(r"^my_playlists/$", my_playlists, name="my_playlists"),
]

pod/urls.py
    url(r'^admin/', admin.site.urls),

    # Translation
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    # App video
    url(r"^videos/$", videos, name="videos"),
    url(r"^rss-video/$", RssSiteVideosFeed(), name="rss-video"),
    url(r"^rss-audio/$", RssSiteAudiosFeed(), name="rss-audio"),
    url(
        r"^rss-video/(?P<slug_c>[\-\d\w]+)/$",
        RssSiteVideosFeed(),
        name="rss-video",
    ),
    url(
        r"^rss-audio/(?P<slug_c>[\-\d\w]+)/$",
        RssSiteAudiosFeed(),
        name="rss-audio",
    ),
    url(
        r"^rss-video/(?P<slug_c>[\-\d\w]+)/(?P<slug_t>[\-\d\w]+)/$",
        RssSiteVideosFeed(),
        name="rss-video",
    ),
    url(
        r"^rss-audio/(?P<slug_c>[\-\d\w]+)/(?P<slug_t>[\-\d\w]+)/$",
        RssSiteAudiosFeed(),
        name="rss-audio",
    ),
    # Manage video owner
    url(
        r"^video/updateowner/put/(?P<user_id>[\d]+)/$",
        update_video_owner,
        name="update_video_owner",
    ),
    url(r"^video/updateowner/owners/$", filter_owners, name="filter_owners"),
    url(
        r"^video/updateowner/videos/(?P<user_id>[\d]+)/$",
        filter_videos,
        name="filter_videos",
    ),
    url(r"^video/(?P<slug>[\-\d\w]+)/$", video, name="video"),
    url(
        r"^video/(?P<slug>[\-\d\w]+)/(?P<slug_private>[\-\d\w]+)/$",
        video,
        name="video_private",
    ),
    url(r"^video_add/$", video_add, name="video_add"),
    url(r"^video_edit/$", video_edit, name="video_edit"),
    url(r"^video_edit/(?P<slug>[\-\d\w]+)/$", video_edit, name="video_edit"),
    url(
        r"^video_delete/(?P<slug>[\-\d\w]+)/$",
        video_delete,
        name="video_delete",
    ),
    url(r"^video_notes/(?P<slug>[\-\d\w]+)/$", video_notes, name="video_notes"),
    url(r"^video_count/(?P<id>[\d]+)/$", video_count, name="video_count"),
    url(r"^video_version/(?P<id>[\d]+)/$", video_version, name="video_version"),
    # url(r'^video_collaborate/(?P<slug>[\-\d\w]+)/$',
    #    video_collaborate,
    #    name='video_collaborate'),
    url(r"^video_xhr/(?P<slug>[\-\d\w]+)/$", video_xhr, name="video_xhr"),
    url(
        r"^video_xhr/(?P<slug>[\-\d\w]+)/(?P<slug_private>[\-\d\w]+)/$",
        video_xhr,
        name="video_xhr",
    ),
    url(
        "api/chunked_upload_complete/",
        PodChunkedUploadCompleteView.as_view(),
        name="api_chunked_upload_complete",
    ),
    url(
        "api/chunked_upload/",
        PodChunkedUploadView.as_view(),
        name="api_chunked_upload",
    ),
    url(r"^ajax_calls/search_user/", user_autocomplete),
    # my channels
    url(r"^my_channels/$", my_channels, name="my_channels"),
    url(
        r"^channel_edit/(?P<slug>[\-\d\w]+)/$",
        channel_edit,
        name="channel_edit",
    ),
    url(r"^theme_edit/(?P<slug>[\-\d\w]+)/$", theme_edit, name="theme_edit"),
    # my videos
    url(r"^my_videos/$", my_videos, name="my_videos"),
    # recording
    url(r"^add_recording/$", add_recording, name="add_recording"),
    url(r"^recorder_notify/$", recorder_notify, name="recorder_notify"),
    url(r"^claim_record/$", claim_record, name="claim_record"),
    url(r"^delete_record/(?P<id>[\d]+)/$", delete_record, name="delete_record"),
    url(r"^search/$", search_videos, name="search_videos"),
    # auth cas
    url(
        r"^authentication_login/$",
        authentication_login,
        name="authentication_login",
    ),
    url(
        r"^authentication_logout/$",
        authentication_logout,
        name="authentication_logout",
    ),
    url(r"^authentication_login/$", authentication_login, name="login"),
    url(r"^authentication_logout/$", authentication_logout, name="logout"),
    url(
        r"^authentication_login_gateway/$",
        authentication_login_gateway,
        name="authentication_login_gateway",
    ),
    url(
        r"^accounts/login/$",
        auth_views.LoginView.as_view(),
        {"redirect_authenticated_user": True},
        name="local-login",
    ),
    url(
        r"^accounts/logout/$",
        auth_views.LogoutView.as_view(),
        {"next_page": "/"},
        name="local-logout",
    ),
    url(r"^accounts/change-password/$", auth_views.PasswordChangeView.as_view()),
    url(r"^accounts/reset-password/$", auth_views.PasswordResetView.as_view()),
    url(r"^accounts/userpicture/$", userpicture, name="userpicture"),
    # rest framework
    url(r"^api-auth/", include("rest_framework.urls")),
    url(r"^rest/", include(rest_urlpatterns)),
    # contact_us
    url(r'^contact_us/$', contact_us, name='contact_us'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^download/$', download_file, name='download_file'),


    # custom
    url(r"^custom/", include("pod.custom.urls")),
]
urlpatterns += (url(r"^maintenance/$", maintenance, name="maintenance"),)

# CAS
if USE_CAS:
    # urlpatterns += [url(r'^sso-cas/', include('cas.urls')), ]
    urlpatterns += [
        url(r"^sso-cas/login/$", cas_views.login, name="cas-login"),
        url(r"^sso-cas/logout/$", cas_views.logout, name="cas-logout"),
    ]

# OIDC
if USE_OIDC:
    urlpatterns += [
        url(r"^oidc/", include("mozilla_django_oidc.urls")),
    ]

# BBB
if USE_BBB:
    urlpatterns += [
        url(r"^bbb/", include("pod.bbb.urls")),
    ]

##
# OEMBED feature patterns
#
if OEMBED:
    urlpatterns += [
        url(r"^oembed/", video_oembed, name="video_oembed"),
    ]

if getattr(settings, "USE_OPENCAST_STUDIO", False):
    urlpatterns += [
        url(r"^studio/", include("pod.recorder.studio_urls")),
    ]

# APPS -> to change !
urlpatterns += [
    url(r"^", include("pod.completion.urls")),
]
urlpatterns += [
    url(r"^", include("pod.chapter.urls")),
]
urlpatterns += [
    url(r"^", include("pod.playlist.urls")),
]

if getattr(settings, "USE_PODFILE", False):
    urlpatterns += [
        url(r"^podfile/", include("pod.podfile.urls")),
    ]

for apps in settings.THIRD_PARTY_APPS:
    urlpatterns += [
        url(r"^" + apps + "/", include("pod.%s.urls" % apps)),
    ]

##
# LTI feature patterns
#
# if getattr(settings, 'LTI_ENABLED', False):
#    # LTI href
#    urlpatterns += [
#        url(r'^lti/', include('lti_provider.urls')),
#        url(r'^assignment/addvideo/',
#            LTIAssignmentAddVideoView.as_view()),
#        url(r'^assignment/getvideo/',
#            LTIAssignmentGetVideoView.as_view()),
#    ]
##
# H5P feature patterns
#
if getattr(settings, "H5P_ENABLED", False):
    urlpatterns += [
        url(r"^h5p/login/", authentication_login, name="h5p_login"),
        url(r"^h5p/logout/", authentication_logout, name="h5p_logout"),
        url(r"^h5p/", include("h5pp.urls")),
    ]

if getattr(settings, "USE_STATS_VIEW", False):
    urlpatterns += [
        url(r"^video_stats_view/$", stats_view, name="video_stats_view"),
        url(
            r"^video_stats_view/(?P<slug>[-\w]+)/$",
            stats_view,
            name="video_stats_view",
        ),
        url(
            r"^video_stats_view/(?P<slug>[-\w]+)/(?P<slug_t>[-\w]+)/$",
            stats_view,
            name="video_stats_view",
        ),
    ]

# COMMENT and VOTE
if getattr(settings, "ACTIVE_VIDEO_COMMENT", False):
    urlpatterns += [
        url(
            r"^comment/(?P<video_slug>[\-\d\w]+)/$",
            get_comments,
            name="get_comments",
        ),
        url(
            r"^comment/(?P<comment_id>[\d]+)/(?P<video_slug>[\-\d\w]+)/$",
            get_children_comment,
            name="get_comment",
        ),
        url(
            r"^comment/add/(?P<video_slug>[\-\d\w]+)/$",
            add_comment,
            name="add_comment",
        ),
        url(
            r"^comment/add/(?P<video_slug>[\-\d\w]+)/(?P<comment_id>[\d]+)/$",
            add_comment,
            name="add_child_comment",
        ),
        url(
            r"^comment/del/(?P<video_slug>[\-\d\w]+)/(?P<comment_id>[\d]+)/$",
            delete_comment,
            name="delete_comment",
        ),
        url(
            r"^comment/vote/(?P<video_slug>[\-\d\w]+)/$",
            vote_get,
            name="get_votes",
        ),
        url(
            r"^comment/vote/(?P<video_slug>[\-\d\w]+)/(?P<comment_id>[\d]+)/$",
            vote_post,
            name="add_vote",
        ),
    ]

# VIDEO CATEGORY
if getattr(settings, "USER_VIDEO_CATEGORY", False):
    urlpatterns += [
        url(r"^my_videos/categories/add/$", add_category, name="add_category"),
        url(
            r"^my_videos/categories/edit/(?P<c_slug>[\-\d\w]+)/$",
            edit_category,
            name="edit_category",
        ),
        url(
            r"^my_videos/categories/delete/(?P<c_id>[\d]+)/$",
            delete_category,
            name="delete_category",
        ),
        url(
            r"^my_videos/categories/(?P<c_slug>[\-\d\w]+)/$",
            get_categories,
            name="get_category",
        ),
        url(r"^my_videos/categories/$", get_categories, name="get_categories"),
    ]


# CHANNELS
urlpatterns += [
    url(r"^(?P<slug_c>[\-\d\w]+)/$", channel, name="channel"),
    url(r"^(?P<slug_c>[\-\d\w]+)/(?P<slug_t>[\-\d\w]+)/$", channel, name="theme"),
    url(
        r"^(?P<slug_c>[\-\d\w]+)/video/(?P<slug>[\-\d\w]+)/$",
        video,
        name="video",
    ),
    url(
        r"^(?P<slug_c>[\-\d\w]+)/(?P<slug_t>[\-\d\w]+)" r"/video/(?P<slug>[\-\d\w]+)/$",
        video,
        name="video",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Change admin site title
admin.site.site_header = _("Pod Administration")

pod/playlist/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _
from pod.video.models import Video
from pod.main.models import get_nextautoincrement


class Playlist(models.Model):
    title = models.CharField(_("Title"), max_length=100, unique=True)
    slug = models.SlugField(
        _("Slug"),
        unique=True,
        max_length=100,
        help_text=_('Used to access this instance, the "slug" is a short label containing only letters, numbers, underscore or dash top.'))
    owner = models.ForeignKey(User, verbose_name=_('Owner'),
                              on_delete=models.CASCADE)
    description = models.TextField(
        _("Description"),
        max_length=255,
        null=True,
        blank=True,
        help_text=_("Short description of the playlist."),
    )
    visible = models.BooleanField(
        _("Visible"),
        default=False,
        help_text=_(
            "If checked, the playlist can be visible to users other than the owner."
        ),
    )

    class Meta:
        ordering = ["title", "id"]
        verbose_name = _("Playlist")
        verbose_name_plural = _("Playlists")

    def save(self, *args, **kwargs):
        newid = -1
        if not self.id:
            try:
                newid = get_nextautoincrement(Playlist)
            except Exception:
                try:
                    newid = Playlist.objects.latest("id").id
                    newid += 1
                except Exception:
                    newid = 1
        else:
            newid = self.id
        newid = "{0}".format(newid)
        self.slug = "{0}-{1}".format(newid, slugify(self.title))
        super(Playlist, self).save(*args, **kwargs)

    def __str__(self):
        return "{0}".format(self.title)

    def first(self):
        return PlaylistElement.objects.get(playlist=self, position=1)

    def last(self):
        last = PlaylistElement.objects.filter(playlist=self).order_by("-position")
        if last:
            return last[0].position + 1
        else:
            return 1

    def videos(self):
        videos = list()
        elements = PlaylistElement.objects.filter(playlist=self)
        for element in elements:
            videos.append(element.video)
        return videos


class PlaylistElement(models.Model):
    playlist = models.ForeignKey(Playlist, verbose_name=_('Playlist'),
                                 on_delete=models.CASCADE)
    video = models.ForeignKey(Video, verbose_name=_('Video'),
                              on_delete=models.CASCADE)
    position = models.PositiveSmallIntegerField(
        _("Position"),
        default=1,
        help_text=_("Position of the video in a playlist."),
    )

    class Meta:
        unique_together = (
            "playlist",
            "video",
        )
        ordering = ["position", "id"]
        verbose_name = _("Playlist element")
        verbose_name_plural = _("Playlist elements")

    def clean(self):
        if self.video.is_draft:
            raise ValidationError(
                _("A video in draft mode cannot be added to a playlist.")
            )
        if self.video.password:
            raise ValidationError(
                _("A video with a password cannot be added to a playlist.")
            )

    def save(self, *args, **kwargs):
        self.full_clean()
        return super(PlaylistElement, self).save(*args, **kwargs)

    def delete(self):
        elements = PlaylistElement.objects.filter(
            playlist=self.playlist, position__gt=self.position
        )
        for element in elements:
            element.position = element.position - 1
            element.save()
        super(PlaylistElement, self).delete()

pod/playlist/forms.py
from django import forms
from django.forms.widgets import HiddenInput
from pod.playlist.models import Playlist


class PlaylistForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PlaylistForm, self).__init__(*args, **kwargs)
        self.fields["owner"].widget = HiddenInput()
        for myField in self.fields:
            self.fields[myField].widget.attrs["class"] = "form-control"
        self.fields["visible"].widget.attrs["class"] = "form-check-input"

    class Meta:
        model = Playlist
        fields = ["title", "description", "visible", "owner"]

pod/playlist/templates/my_playlists.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block page_extra_head %}
	<link href="{% static 'css/playlist.css' %}?ver={{VERSION}}" rel="stylesheet">
	<script src="{% static 'js/playlist.js' %}?ver={{VERSION}}"></script>
{% endblock page_extra_head %}

{% block breadcrumbs %}{{ block.super }} <li class="breadcrumb-item active" aria-current="page">{% trans "My playlists" %}</li>{% endblock %}

{% block page_title %}
	{% blocktrans count counter=playlists.paginator.count %}{{ counter }} playlist found{% plural %}{{ counter }} playlists found{% endblocktrans %}
{% endblock %}

{% block page_content %}
	{% if playlists.paginator.count == 0 %}
		<p class="text-info">{% trans 'No playlist found' %}</p>
		<p class="alert alert-info">{% trans 'You have not created any playlists yet, please use the "Add a new playlist" button to add one.' %}</p>
		<a href="{% url 'playlist_edit' %}" class="btn btn-primary"><i data-feather="plus" aria-hidden="true"></i>{% trans 'Add a new playlist' %}</a>
	{% else %}
		<p class="text-info">{% blocktrans count counter=playlists.paginator.count %}{{ counter }} playlist found{% plural %}{{ counter }} playlists found{% endblocktrans %}</p>
		{% include 'playlist/playlist_list.html' %}
	{% endif %}
	<hr/>
	<p>{% trans 'This is the page of your playlists. Here you can create, edit or delete them.' %}</p>
	<p>{% trans 'A playlist with the eye symbol means that this playlist is visible to all users when they view this page.' %}</p>
{% endblock page_content %}

{% block collapse_page_aside %}{% endblock collapse_page_aside %}
{% block page_aside %}{% endblock page_aside %}

pod/playlist/templates/playlist.html
<!-- HTML for playlist management. -->
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block page_extra_head %}
  <link href="{% static 'css/playlist.css' %}?ver={{VERSION}}" rel="stylesheet">
  <script src="{% static 'js/playlist.js' %}?ver={{VERSION}}"></script>
{% endblock page_extra_head %}

{% block breadcrumbs %}
  {{block.super}}
  <li class="breadcrumb-item">
    <a href="{% url 'my_playlists' %}">{% trans 'My playlists' %}</a>
  </li>
  {% if form.instance.title %}
    <li class="breadcrumb-item">
      {{form.instance.title}}
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      {% trans "Edit" %}
    </li>
  {% else %}
    <li class="breadcrumb-item active" aria-current="page">
      {% trans "Add a new playlist" %}
    </li>
  {% endif %}
{% endblock %}

{% block page_title %}
  {% if form.instance.title %}{% trans 'Editing the playlist' %} "{{form.instance.title}}"{% else %}{% trans 'Add a new playlist' %}{%endif%}
{% endblock %}

{% block page_content %}
  <h1 class="page_title">
    {% if form.instance.title %}
      {% trans 'Editing the playlist' %} "{{form.instance.title}}"
    {% else %}
      {% trans 'Add a new playlist' %}
    {% endif %}
  </h1>
  <form id="playlist_form" method="POST"
    {% if form.instance.slug %}
      action="{% url 'playlist_edit' slug=form.instance.slug %}"
    {% else %}
      action="{% url 'playlist_edit' %}"
    {% endif %}
  >
    {% csrf_token %}
    {% for field_hidden in form.hidden_fields %}
      {{field_hidden}}
    {% endfor %}
    {% for field in form.visible_fields %}
      {% if field.name == 'visible' %}
        <div class="form-check">
          {{field.errors}}
          {{field}}
          <label for="{{field.id_for_label}}" class="form-check-label">{{field.label}}</label>
      {% else %}
        <div class="form-group {% if field.field.required %}form-group-required {% endif %}">
          {{field.errors}}
          <label for="{{field.id_for_label}}">{{field.label}}</label>
          {{field}}
      {% endif %}
        </div>
    {% endfor %}
    <div class="text-center">
      <input type="hidden" name="action" value="edit"/>
      <input type="submit" value="{% trans 'Save' %}" class="btn btn-primary"/>
      <a class="playlist-delete btn btn-primary" href="#">{% csrf_token %}{% trans 'Delete' %}</a>
    </div>
  </form>
  <hr/>
  {% if form.instance.playlistelement_set.all %}
    {% include 'playlist/playlist_element_list.html' %}
  {% else %}
    <p>{% trans 'This playlist has no videos yet.' %}</p>
  {% endif %}
  <hr/>
  <a href="{% url 'my_playlists' %}" class="btn btn-secondary">{% trans 'Back to my playlists' %}</a>
{% endblock page_content %}

pod/playlist/templates/playlist_player-iframe.html
{% extends 'videos/video-iframe.html' %}
{% load i18n %}
{% load static %}

{% block page_extra_head %}
{% include 'videos/video-header.html' %}
<link href="{% static 'css/videojs-playlist.css' %}?ver={{VERSION}}" rel="stylesheet">
<script src="{% static 'js/videojs-playlist-controlbar.js' %}?ver={{VERSION}}"></script>
<script src="{% static 'js/playlist_player.js' %}?ver={{VERSION}}"></script>
<link rel="stylesheet" href="{% static 'css/playlist-iframe.css' %}?ver={{VERSION}}">
{% endblock page_extra_head %}

{% block breadcrumbs %}{{ block.super }}{% endblock %}

{% block page_title %}{%if channel %}{{channel.title}} - {%endif%}{%if theme %}{{theme.title}} - {%endif%}({% trans 'Enriched' %}) {{video.title}}{% endblock %}

{% block page_content %}
<div class="overlay playlist" id="div-video-wrapper">
{% include 'playlist/playlist_video_list.html' with is_iframe=True %}

{% block video-element %}
{% if form %}
  {% include 'videos/video-form.html' %}
{% else %}
  <video id="podvideoplayer"></video>
{%endif%}
{% endblock video-element %}

  <div id="info-video-wrapper" class="jumbotron">
    <div class="iframe-header bg-dark text-white">
      <h2 class="playlist-video-title">{{ video.title }}</h2>
      <button type="button" class="close" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div id="info-video"></div>
  </div>
  <div id="overlay-footer"><p class="playlist-video-title">
      {{ video.title|safe}}
  </p></div>
</div>

{% block more_script %}
{% if not form %}
  {% include 'videos/video-script.html'%}
  <script>
    player.videoJsInfo();
    player.videoJsPlaylist();
    function setOnPlayerPlayPause() {
      player.on('play',function() {
        isPlaying = true;
        $('#div-video-wrapper').attr('class','')
      })
      player.on('pause',function() {isPlaying = false;})
      player.ready(function() {
        $('#div-video-wrapper').addClass('vjs-not-started')
      })
    }
    player.ready(function() {
      const btinfo = $('.vjs-info-button:eq(0)')[0]
          , btplaylist = $('.vjs-playlist-button:eq(0)')[0]
      $(btinfo).clone().appendTo('#overlay-footer')
      $(btplaylist).clone().appendTo('#overlay-footer');
      $('#overlay-footer .vjs-info-button').click(function(){$(btinfo).click()})
      $('#overlay-footer .vjs-playlist-button').click(function(){$(btplaylist).click()})
    })

    const show_video_playlist = function() {
      const hasStarted = $(player.el()).hasClass('vjs-has-started')
          , isOverlayed = $('#div-video-wrapper').hasClass('overlay')
          , isInfoOverlayed = isOverlayed && $('#div-video-wrapper').hasClass('playlist')
          , cls = 'overlay playlist'
      if(!isOverlayed) { // No overlay is displayed
        wasPlaying = isPlaying;
        player.pause();
        $('#div-video-wrapper').attr('class', cls)
        resizePlaylist()
      } else if(!isInfoOverlayed) { // One overlay is displayed but not Info
        $('#div-video-wrapper').attr('class', cls)
        resizePlaylist()
      } else { // Info overlay is displayed => close it
        $('#div-video-wrapper').attr('class', (hasStarted ? '' : 'vjs-not-started'))
        if(wasPlaying) player.play();
      }
    };
    const resizePlaylist = function() {
      const ihead = document.querySelector('#card-playlist > .iframe-header')
          , ph = player.el().offsetHeight
          , pb = parseInt(player.el().style.top) + ph - 30
          , pw = ph*hdres//$('#podvideoplayer .vjs-poster').width()
      $('#card-playlist > div.card-body').css('top',ihead.offsetHeight+'px')
      //console.log('MTop: '+player.el().style.top+'\nleft: '+player.el().offsetLeft+'\nwidth: '+player.el().offsetWidth+'\nheight: '+player.el().offsetHeight+' /// '+pb)
      $('#card-playlist').css({top:player.el().style.top, height:(ph - 30)+'px', left: '50%', 'margin-left': -(pw/2)+'px', width: pw+'px'})
      $('#overlay-footer').css({'top':pb+'px'})
    }
    $('#card-playlist .link-center-pod, #card-playlist .card-body > span > a').each(function() {
       $(this).attr('href',($(this).attr('href').indexOf('?') > 0 ? $(this).attr('href')+'&is_iframe=true'
                                                                  : $(this).attr('href')+'?is_iframe=true'));
    })
    $(document).on('click', '.close', function() {
        if($(this).hasClass('playlist')) {
          show_video_playlist()
        } else {
          show_info_video()
        }
    });

{% endif %}

// Responsive
const hdres = 1920/1080;
let isPlaying = false, wasPlaying = false
setOnPlayerPlayPause()
function resizeInfo() {
  const ihead = document.querySelector('#info-video-wrapper > .iframe-header')
      , ph = player.el().offsetHeight
      , pb = parseInt(player.el().style.top) + ph - 30
      , pw = ph*hdres//$('#podvideoplayer .vjs-poster').width()
  $('#info-video').css('top',ihead.offsetHeight+'px')
  //console.log('MTop: '+player.el().style.top+'\nleft: '+player.el().offsetLeft+'\nwidth: '+player.el().offsetWidth+'\nheight: '+player.el().offsetHeight+' /// '+pb)
  $('#info-video-wrapper').css({top:player.el().style.top, height:(ph - 30)+'px', left: '50%', 'margin-left': -(pw/2)+'px', width: pw+'px'})
  $('#overlay-footer').css({'top':pb+'px'})
}
function resizeVideoJs(){
  const width = document.getElementById(player.id()).parentElement.offsetWidth
      , height = document.getElementById(player.id()).parentElement.offsetHeight
      , ratio = width/height;
  let margintop = 0
  if(ratio<hdres) {
    player.width(width);
    player.height(width / hdres);
    margintop = parseInt((height - player.height())/2);
    document.getElementById("podvideoplayer").style.top = margintop+"px";
  } else {
    player.height(height);
    player.width(height*hdres);
    document.getElementById("podvideoplayer").style.top = "0";
  }
  resizeInfo()
  resizePlaylist();
}
resizeVideoJs(); // Initialize the function right now
window.onresize = resizeVideoJs; // Call the function on resize
const show_info_video = function() { // Call by videojs-playlist-controllbar
  const hasStarted = $(player.el()).hasClass('vjs-has-started')
      , isOverlayed = $('#div-video-wrapper').hasClass('overlay')
      , isInfoOverlayed = isOverlayed && $('#div-video-wrapper').hasClass('info')
      , cls = 'overlay info'
  if(!isOverlayed) { // No overlay is displayed
    wasPlaying = isPlaying;
    player.pause();
    $('#div-video-wrapper').attr('class', cls)
    resizeInfo()
  } else if(!isInfoOverlayed) { // One overlay is displayed but not Info
    $('#div-video-wrapper').attr('class', cls)
    resizeInfo()
  } else { // Info overlay is displayed => close
    $('#div-video-wrapper').attr('class', (hasStarted ? '' : 'vjs-not-started'))
    if(wasPlaying) player.play();
  }
}
$('#video-meta .tab-pane').addClass('show').show();
</script>
{% endblock more_script %}
{% endblock page_content %}