pod/enrichment/urls.py
from django.conf.urls import url
from .views import edit_enrichment
from .views import video_enrichment
from .views import group_enrichment

app_name = "enrichment"

urlpatterns = [
    url(r"^edit/(?P<slug>[\-\d\w]+)/$", edit_enrichment, name="edit_enrichment"),
    url(
        r"^group/(?P<slug>[\-\d\w]+)/$",
        group_enrichment,
        name="group_enrichment",
    ),
    url(
        r"^video/(?P<slug>[\-\d\w]+)/$",
        video_enrichment,
        name="video_enrichment",
    ),
    url(
        r"^video/(?P<slug>[\-\d\w]+)/(?P<slug_private>[\-\d\w]+)/$",
        video_enrichment,
        name="video_enrichment_private",
    ),
]

pod/urls.py
"""Esup-pod URL configuration."""

from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.i18n import JavaScriptCatalog
from django.utils.translation import ugettext_lazy as _

from pod.authentication.views import authentication_login
from pod.authentication.views import authentication_logout
from pod.authentication.views import authentication_login_gateway
from pod.authentication.views import userpicture

from pod.video.views import video
from pod.video.views import video_edit
from pod.video.views import video_add
from pod.video.views import video_delete

# from pod.video.views import video_collaborate
from pod.video.views import channel
from pod.video.views import videos
from pod.video.views import my_videos
from pod.video.views import my_channels
from pod.video.views import channel_edit
from pod.video.views import theme_edit
from pod.video.views import video_notes
from pod.video.views import video_xhr
from pod.video.views import video_count, video_version
from pod.video.views import video_oembed
from pod.video.views import stats_view
from pod.video.views import get_comments, get_children_comment
from pod.video.views import add_comment, delete_comment
from pod.video.views import vote_get, vote_post
from pod.video.views import get_categories, add_category
from pod.video.views import edit_category, delete_category
from pod.video.views import update_video_owner, filter_owners, filter_videos
from pod.video.feeds import RssSiteVideosFeed, RssSiteAudiosFeed
from pod.main.views import (
    contact_us,
    download_file,
    user_autocomplete,
    maintenance,
    robots_txt,
)
from pod.main.rest_router import urlpatterns as rest_urlpatterns
from pod.video_search.views import search_videos
from pod.recorder.views import (
    add_recording,
    recorder_notify,
    claim_record,
    delete_record,
)
# from pod.lti.views import LTIAssignmentAddVideoView, LTIAssignmentGetVideoView
from pod.video.views import PodChunkedUploadView, PodChunkedUploadCompleteView


USE_CAS = getattr(settings, "USE_CAS", False)
USE_SHIB = getattr(settings, "USE_SHIB", False)
USE_OIDC = getattr(settings, "USE_OIDC", False)
OEMBED = getattr(settings, "OEMBED", False)
USE_BBB = getattr(settings, "USE_BBB", False)

if USE_CAS:
    from cas import views as cas_views


urlpatterns = [
    url("select2/", include("django_select2.urls")),
    url("robots.txt", robots_txt),
    url(r'^admin/', admin.site.urls),

    # Translation
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    # App video
    url(r"^videos/$", videos, name="videos"),
    url(r"^rss-video/$", RssSiteVideosFeed(), name="rss-video"),
    url(r"^rss-audio/$", RssSiteAudiosFeed(), name="rss-audio"),
    url(
        r"^rss-video/(?P<slug_c>[\-\d\w]+)/$",
        RssSiteVideosFeed(),
        name="rss-video",
    ),
    url(
        r"^rss-audio/(?P<slug_c>[\-\d\w]+)/$",
        RssSiteAudiosFeed(),
        name="rss-audio",
    ),
    url(
        r"^rss-video/(?P<slug_c>[\-\d\w]+)/(?P<slug_t>[\-\d\w]+)/$",
        RssSiteVideosFeed(),
        name="rss-video",
    ),
    url(
        r"^rss-audio/(?P<slug_c>[\-\d\w]+)/(?P<slug_t>[\-\d\w]+)/$",
        RssSiteAudiosFeed(),
        name="rss-audio",
    ),
    # Manage video owner
    url(
        r"^video/updateowner/put/(?P<user_id>[\d]+)/$",
        update_video_owner,
        name="update_video_owner",
    ),
    url(r"^video/updateowner/owners/$", filter_owners, name="filter_owners"),
    url(
        r"^video/updateowner/videos/(?P<user_id>[\d]+)/$",
        filter_videos,
        name="filter_videos",
    ),
    url(r"^video/(?P<slug>[\-\d\w]+)/$", video, name="video"),
    url(
        r"^video/(?P<slug>[\-\d\w]+)/(?P<slug_private>[\-\d\w]+)/$",
        video,
        name="video_private",
    ),
    url(r"^video_add/$", video_add, name="video_add"),
    url(r"^video_edit/$", video_edit, name="video_edit"),
    url(r"^video_edit/(?P<slug>[\-\d\w]+)/$", video_edit, name="video_edit"),
    url(
        r"^video_delete/(?P<slug>[\-\d\w]+)/$",
        video_delete,
        name="video_delete",
    ),
    url(r"^video_notes/(?P<slug>[\-\d\w]+)/$", video_notes, name="video_notes"),
    url(r"^video_count/(?P<id>[\d]+)/$", video_count, name="video_count"),
    url(r"^video_version/(?P<id>[\d]+)/$", video_version, name="video_version"),
    # url(r'^video_collaborate/(?P<slug>[\-\d\w]+)/$',
    #    video_collaborate,
    #    name='video_collaborate'),
    url(r"^video_xhr/(?P<slug>[\-\d\w]+)/$", video_xhr, name="video_xhr"),
    url(
        r"^video_xhr/(?P<slug>[\-\d\w]+)/(?P<slug_private>[\-\d\w]+)/$",
        video_xhr,
        name="video_xhr",
    ),
    url(
        "api/chunked_upload_complete/",
        PodChunkedUploadCompleteView.as_view(),
        name="api_chunked_upload_complete",
    ),
    url(
        "api/chunked_upload/",
        PodChunkedUploadView.as_view(),
        name="api_chunked_upload",
    ),
    url(r"^ajax_calls/search_user/", user_autocomplete),
    # my channels
    url(r"^my_channels/$", my_channels, name="my_channels"),
    url(
        r"^channel_edit/(?P<slug>[\-\d\w]+)/$",
        channel_edit,
        name="channel_edit",
    ),
    url(r"^theme_edit/(?P<slug>[\-\d\w]+)/$", theme_edit, name="theme_edit"),
    # my videos
    url(r"^my_videos/$", my_videos, name="my_videos"),
    # recording
    url(r"^add_recording/$", add_recording, name="add_recording"),
    url(r"^recorder_notify/$", recorder_notify, name="recorder_notify"),
    url(r"^claim_record/$", claim_record, name="claim_record"),
    url(r"^delete_record/(?P<id>[\d]+)/$", delete_record, name="delete_record"),
    url(r"^search/$", search_videos, name="search_videos"),
    # auth cas
    url(
        r"^authentication_login/$",
        authentication_login,
        name="authentication_login",
    ),
    url(
        r"^authentication_logout/$",
        authentication_logout,
        name="authentication_logout",
    ),
    url(r"^authentication_login/$", authentication_login, name="login"),
    url(r"^authentication_logout/$", authentication_logout, name="logout"),
    url(
        r"^authentication_login_gateway/$",
        authentication_login_gateway,
        name="authentication_login_gateway",
    ),
    url(
        r"^accounts/login/$",
        auth_views.LoginView.as_view(),
        {"redirect_authenticated_user": True},
        name="local-login",
    ),
    url(
        r"^accounts/logout/$",
        auth_views.LogoutView.as_view(),
        {"next_page": "/"},
        name="local-logout",
    ),
    url(r"^accounts/change-password/$", auth_views.PasswordChangeView.as_view()),
    url(r"^accounts/reset-password/$", auth_views.PasswordResetView.as_view()),
    url(r"^accounts/userpicture/$", userpicture, name="userpicture"),
    # rest framework
    url(r"^api-auth/", include("rest_framework.urls")),
    url(r"^rest/", include(rest_urlpatterns)),
    # contact_us
    url(r'^contact_us/$', contact_us, name='contact_us'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^download/$', download_file, name='download_file'),


    # custom
    url(r"^custom/", include("pod.custom.urls")),
]
urlpatterns += (url(r"^maintenance/$", maintenance, name="maintenance"),)

# CAS
if USE_CAS:
    # urlpatterns += [url(r'^sso-cas/', include('cas.urls')), ]
    urlpatterns += [
        url(r"^sso-cas/login/$", cas_views.login, name="cas-login"),
        url(r"^sso-cas/logout/$", cas_views.logout, name="cas-logout"),
    ]

# OIDC
if USE_OIDC:
    urlpatterns += [
        url(r"^oidc/", include("mozilla_django_oidc.urls")),
    ]

# BBB
if USE_BBB:
    urlpatterns += [
        url(r"^bbb/", include("pod.bbb.urls")),
    ]

##
# OEMBED feature patterns
#
if OEMBED:
    urlpatterns += [
        url(r"^oembed/", video_oembed, name="video_oembed"),
    ]

if getattr(settings, "USE_OPENCAST_STUDIO", False):
    urlpatterns += [
        url(r"^studio/", include("pod.recorder.studio_urls")),
    ]

# APPS -> to change !
urlpatterns += [
    url(r"^", include("pod.completion.urls")),
]
urlpatterns += [
    url(r"^", include("pod.chapter.urls")),
]
urlpatterns += [
    url(r"^", include("pod.playlist.urls")),
]

if getattr(settings, "USE_PODFILE", False):
    urlpatterns += [
        url(r"^podfile/", include("pod.podfile.urls")),
    ]

for apps in settings.THIRD_PARTY_APPS:
    urlpatterns += [
        url(r"^" + apps + "/", include("pod.%s.urls" % apps)),
    ]

##
# LTI feature patterns
#
# if getattr(settings, 'LTI_ENABLED', False):
#    # LTI href
#    urlpatterns += [
#        url(r'^lti/', include('lti_provider.urls')),
#        url(r'^assignment/addvideo/',
#            LTIAssignmentAddVideoView.as_view()),
#        url(r'^assignment/getvideo/',
#            LTIAssignmentGetVideoView.as_view()),
#    ]
##
# H5P feature patterns
#
if getattr(settings, "H5P_ENABLED", False):
    urlpatterns += [
        url(r"^h5p/login/", authentication_login, name="h5p_login"),
        url(r"^h5p/logout/", authentication_logout, name="h5p_logout"),
        url(r"^h5p/", include("h5pp.urls")),
    ]

if getattr(settings, "USE_STATS_VIEW", False):
    urlpatterns += [
        url(r"^video_stats_view/$", stats_view, name="video_stats_view"),
        url(
            r"^video_stats_view/(?P<slug>[-\w]+)/$",
            stats_view,
            name="video_stats_view",
        ),
        url(
            r"^video_stats_view/(?P<slug>[-\w]+)/(?P<slug_t>[-\w]+)/$",
            stats_view,

pod/enrichment/forms.py
from django import forms
from django.conf import settings
from django.forms.widgets import HiddenInput
from django.contrib.admin import widgets
from django.utils.translation import ugettext_lazy as _
from django.utils.safestring import mark_safe
from .models import Enrichment, EnrichmentGroup, EnrichmentVtt
from django.contrib.auth.models import Group
from django.contrib.sites.shortcuts import get_current_site

FILEPICKER = False
if getattr(settings, "USE_PODFILE", False):
    FILEPICKER = True
    from pod.podfile.widgets import CustomFileWidget


class EnrichmentAdminForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EnrichmentAdminForm, self).__init__(*args, **kwargs)
        if FILEPICKER:
            self.fields["image"].widget = CustomFileWidget(type="image")
            self.fields["document"].widget = CustomFileWidget(type="file")

    class Meta(object):
        model = Enrichment
        fields = "__all__"


class EnrichmentGroupForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EnrichmentGroupForm, self).__init__(*args, **kwargs)
        self.fields["groups"].widget = widgets.FilteredSelectMultiple(
            _("Groups"), False, attrs={}
        )
        self.fields["groups"].queryset = Group.objects.all().filter(
            groupsite__sites=get_current_site(None)
        )

    class Meta(object):
        model = EnrichmentGroup
        fields = ("groups",)  # '__all__'


class EnrichmentForm(forms.ModelForm):
    """Define edit forms for all enrichments types."""

    def __init__(self, *args, **kwargs):
        """Init an EnrichmentForm."""
        super(EnrichmentForm, self).__init__(*args, **kwargs)
        self.fields["video"].widget = HiddenInput()
        self.fields["start"].widget.attrs["min"] = 0
        self.fields["end"].widget.attrs["min"] = 1
        try:
            self.fields["start"].widget.attrs["max"] = self.instance.video.duration
            self.fields["end"].widget.attrs["max"] = self.instance.video.duration
        except Exception:
            self.fields["start"].widget.attrs["max"] = 36000
            self.fields["end"].widget.attrs["max"] = 36000
        for myField in self.fields:
            if self.fields[myField].required or myField == "type":
                self.fields[myField].widget.attrs["class"] = "form-control required"
                label_unicode = "{0}".format(self.fields[myField].label)
                self.fields[myField].label = mark_safe(
                    "{0} <span class='required_star'>*</span>".format(label_unicode)
                )
            else:
                self.fields[myField].widget.attrs["class"] = "form-control"
        self.fields["type"].widget.attrs["class"] = "custom-select"
        if FILEPICKER:
            self.fields["image"].widget = CustomFileWidget(type="image")
            self.fields["document"].widget = CustomFileWidget(type="file")

    class Meta(object):
        model = Enrichment
        fields = "__all__"


class EnrichmentVttAdminForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EnrichmentVttAdminForm, self).__init__(*args, **kwargs)
        if FILEPICKER:
            self.fields["src"].widget = CustomFileWidget(type="file")

    class Meta(object):
        model = EnrichmentVtt
        fields = "__all__"

pod/enrichment/templates/enrichment/edit_enrichment.html
{% extends 'enrichment/video_enrichment.html' %}
{% load i18n %}
{% load static %}

{% block page_title %}{% trans 'Enrichment of the video' %} "{{video.title}}" {% endblock page_title %}

{% block page_extra_head %}

{{ block.super }}

<link rel="stylesheet" href="{% static 'css/enrichment.css' %}?ver={{VERSION}}"/>
<script src="{% static 'js/enrichment.js' %}?ver={{VERSION}}"></script>

<!-- form.media -->
<script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}?ver={{VERSION}}"></script>

<script>
  var num = 0,
  name = '';
  /*** For the form ***/;
  var video_duration = {{video.duration}};
  /*** For the Cancel button ***/
  $(document).on("reset", "#page-video form", function (e) {
    $("span#form_enrich").html("");
    $("form#form_new").show();
    $("form").show();
    $("table tr").removeClass("info");
    manageResize();
  });
</script>
{% endblock page_extra_head %}

{% block video-element %}
<div id="page-video">
  {% include 'enrichment/video-element-enrichment.html' %}
  <hr/>

  <div id="info_video">
    <div id="list_enrich">
      {% include 'enrichment/list_enrichment.html' %}
    </div>
    <div id="form_enrich">
      {% if form_enrichment %}
        {% include 'enrichment/form_enrichment.html' with form_enrichment=form_enrichment %}
      {% endif %}
    </div>
    {% if not form_enrichment %}
      <form id="form_new" class="get_form" action="{% url 'enrichment:edit_enrichment' slug=video.slug %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="action" value="new"/>
        <input type="submit" id="add_new_enrichment" value="{% trans 'Add a new enrichment' %}" class="btn btn-primary btn-sm"/>
      </form>
    {% endif %}
    <hr/>
    <div class="d-flex justify-content-between">
    <a href="{% url 'video_edit' slug=video.slug %}" class="btn btn-secondary btn-sm" title="{% trans 'Back to video edit' %}">
      {% trans 'Back to video edit' %}
    </a>
    <a href="{% url 'enrichment:video_enrichment' slug=video.slug %}" class="btn btn-primary btn-sm" title="{% trans 'See the enrich video' %}">
      {% trans 'See the enrich video' %}
    </a>
    </div>
  </div>
</div>
{% endblock video-element %}

{% block page_aside %}
<div class="card" id="card-enrichmenteditinformations">
  <h5 class="card-header card-title ps-2">
    <i class="bi bi-info-circle"></i>&nbsp;{% trans 'Editing enrichments' %}
  </h5>
  <div class="card-body card-text small">
    {% if video.owner == request.user or request.user.is_superuser or perms.enrichment.change_enrichment or request.user in video.additional_owners.all %}
      <p><a href="{% url 'enrichment:group_enrichment' slug=video.slug %}" title="{% trans 'You can specify the group(s) of users who can access this page' %}"><i class="bi bi-people"></i>&nbsp;{% trans 'You can specify the group(s) of users who can access this page' %}</a></p>
    {% endif %}
    <p>{% trans 'The title field is required and must contains from 2 to 100 characters.' %}</p>
    <p>{% trans 'The fields "Start" and "End" must contain an indication value in seconds. Start playback of the video, pause the video and click on "Get time from the player" to fill in the field untitled "Start". Then do the same to fill in the field untitled "End".' %}</p>
    <p>{% trans 'You cannot overlap enrichments.' %}</p>
    <p>{% trans 'You must save your enrichments to view the result.' %}</p>
  </div>
</div>
{{ block.super }}
{% endblock page_aside %}

{% block more_script %}
{{block.super}}
{% endblock more_script %}

pod/enrichment/templates/enrichment/form_enrichment.html
{# HTML for enrichment form. Don't use this file alone it must be integrated into another template! #}
{% load i18n %}
{% load static %}
{{form_enrichment.media}}
<div class="panel-heading">
    <h4 class="card-title">{% trans 'Create / Edit enrichment' %}</h4>
</div>
<form id="form_enrich" class="form_save" action="{% url 'enrichment:edit_enrichment' slug=video.slug %}" method="POST">
    {% csrf_token %}
    <div id="formcontent" class="form-container">
        {% if form_enrichment.errors or form_enrichment.non_field_errors %}
            <div class="alert alert-danger">
                {% trans 'One or more errors have been found in the form:' %}
                <ul>{% for error in form_enrichment.non_field_errors %}
                    <li>{{error}}</li>
                {% endfor %}</ul>
            </div>
        {% endif %}
        {% for field_hidden in form_enrichment.hidden_fields %}
            {{field_hidden}}
        {% endfor %}
        {% for field in form_enrichment.visible_fields %}
            <div class="form-group row">
                <label for="{{field.auto_id}}" class="col-sm-2 col-form-label">{{field.label}}</label>
                <div class="col-sm-10">
                    {{field}}
                    {% if field.help_text %}
                      <small id="{{field.id_for_label}}Help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        {% if form_enrichment.instance %}
            <input type="hidden" id="id_enrich" name="enrich_id" value="{{form_enrichment.instance.id}}"/>
        {% endif %}
        <input type="hidden" name="action" value="save"/>
        <input type="submit" id="save_enrichment" value="{% trans 'Save' %}" class="btn btn-primary btn-sm"/>
        <input type="reset" action="cancel" id="cancel_enrichment" value="{% trans 'Cancel' %}" class="btn btn-secondary btn-sm" />
    </div>
</form>

pod/enrichment/templates/enrichment/group_enrichment.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block page_extra_head %}

{% endblock page_extra_head %}

{% block breadcrumbs %}{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'my_videos' %}">{% trans 'My videos' %}</a></li>
<li class="breadcrumb-item active" aria-current="page">{% trans "Editing group for the enrichment of the video" %}</li>
{% endblock %}

{% block page_title %}{% trans "Editing group for the enrichment of the video" %} "{{video.title}}"{% endblock %}


{% block page_content %}
{% spaceless %}
<h3>{% trans "Editing group for the enrichment of the video" %} "{{video.title}}"
</h3>

<form id="enrichment_group_form" method="post"
  action="{% url 'enrichment:group_enrichment' slug=video.slug %}"
  accept-charset="utf-8" class="needs-validation" novalidate>
  {% csrf_token %}
  <div class="list-group">
    <fieldset>
      {% if form.errors %}
        <p class="text-danger">{% trans "One or more errors have been found in the form." %}</p>
        {{form.errors}}
      {% endif %}
      {% if form.instance.encoding_in_progress %}
        <div class="alert alert-warning" role="alert">
          {% trans "The video is currently being encoded." %}
        </div>
      {% endif %}
      {% for field_hidden in form.hidden_fields %}
        {{field_hidden}}
      {% endfor %}
      {% for field in form.visible_fields %}
        {% spaceless %}
        <div class="{% if "description_" in field.name or "title_"  in field.name %}collapse hide{% else %}{% endif %}{% if "description_" in field.name %} description{%endif%}{% if "title_" in field.name %} title{%endif%}">
          <div class="list-group-item">
            <div class="{% if field.name == "groups"%}form-row {%endif%}form-group {% if field.field.required %}form-group-required{%endif%}">
              {{ field.errors }}
              <label for="{{ field.id_for_label }}">{{ field.label }}&nbsp;</label>
              {{ field }}
              {% if field.help_text %}
                <small id="{{field.id_for_label}}Help" class="form-text text-muted">{{ field.help_text|safe }}</small>
              {% endif %}
              {% if field.field.required %}<div class="invalid-feedback">{% trans "Please provide a valid value for this field" %}.</div>{%endif%}
            </div>
          </div>
        </div>
        {% endspaceless %}
      {% endfor %}
    </fieldset>
  </div>
  <div class="text-center">
    <button type="submit" class="btn btn-primary btn-sm" name="_continue" value="">{% trans 'Save' %}</button>
    <a href="{% url 'enrichment:edit_enrichment' slug=video.slug %}" title="{% trans 'back to editing enrichment' %}" class="btn btn-secondary btn-sm">{% trans 'back to editing enrichment' %}</a>
  </div>
</form>

{% endspaceless %}
{% endblock page_content %}

{% block page_aside %}
{% if video.owner == request.user or request.user.is_superuser or perms.video.change_video or request.user in video.additional_owners.all %}
  <div class="card" id="card-managevideo">
    <h2 class="card-header card-title ps-2 h4"><i class="bi bi-gear"></i>&nbsp;{% trans "Manage video"%}</h2>
    <div class="card-body card-text text-center">
      {% include "videos/link_video.html" %}
    </div>
  </div>
{% endif %}
{% endblock page_aside %}

{% block more_script %}
  <script src="/admin/jsi18n/"></script>
  <script src="{% static 'admin/js/core.js' %}?ver={{VERSION}}"></script>
  <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}?ver={{VERSION}}"></script>
  <script src="{% static 'admin/js/jquery.init.js' %}?ver={{VERSION}}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}?ver={{VERSION}}" />
  {{form.media}}
{% endblock more_script %}

pod/enrichment/templates/enrichment/list_enrichment.html
{# HTML for enrichment list. Don't use this file alone it must be integrated into another template! #}
{% load i18n %}
<div class="container" overflow: auto>
	<div class="panel-heading">
		<h4 class="card-title">{% trans 'List of the enrichments' %}&nbsp;({{list_enrichment|length}})</h4>
	</div>
	<table class="table table-striped table-condensed scroll" id="table_list_enrich">
		<thead>
			<tr>
				<th scope="col">{% trans 'Title' %}</th>
				<th scope="col">{% trans 'Type' %}</th>
				<th scope="col" class="enrich_start">{% trans 'Start' %}</th>
				<th scope="col" class="enrich_end">{% trans 'End' %}</th>
				<th scope="col">{% trans 'Actions' %}</th>
			</tr>
		</thead>
		<tbody>
			{% for enrich in list_enrichment %}
				<tr>
					<td class="enrich_title">{{enrich.title}}</td>
					<td class="enrich_type enrich_{{enrich.type}}">{% if enrich.type %}{% trans enrich.type %}{% endif %}</td>
					<td class="enrich_start">{{enrich.start}}</td>
					<td class="enrich_end">{{enrich.end}}</td>
					<td>
						<form class="get_form" action="{% url 'enrichment:video_enrichment' slug=video.slug %}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="action" value="modify"/>
							<input type="hidden" name="id" value="{{enrich.id}}"/>
							<input type="submit" title="{% trans 'Edit the enrichment' %}" value="{% trans 'Modify' %}" class="btn btn-primary btn-sm"/>
						</form>
						<form class="get_form" action="{% url 'enrichment:video_enrichment' slug=video.slug %}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="action" value="delete"/>
							<input type="hidden" name="id" value="{{enrich.id}}"/>
							<input type="submit" title="{% trans 'Delete the enrichment' %}" value="{% trans 'Delete' %}" class="btn btn-danger btn-sm"/>
						</form>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

pod/enrichment/templates/enrichment/video-element-enrichment.html
{% extends 'videos/video-element.html' %}
{% block extratrack %}
{% if video.enrichment_set.all %}
<track kind="metadata" src="{{video.enrichmentvtt.src.file.url}}?{% now "U" %}" label="enrichment">
{% endif %}
{% endblock extratrack %}

pod/enrichment/templates/enrichment/video_enrichment-iframe.html
{% extends 'videos/video-iframe.html' %}
{% load i18n %}
{% load static %}

{% block page_extra_head %}
{% include 'videos/video-header.html' %}
<link id="enrichment_style_id" href="{% static 'css/videojs-slides.css' %}?ver={{VERSION}}" rel="stylesheet">
<script id="enrichment_script_id" src="{% static 'js/videojs-slides.js' %}?ver={{VERSION}}"></script>
{% endblock page_extra_head %}

{% block page_title %}{%if channel %}{{channel.title}} - {%endif%}{%if theme %}{{theme.title}} - {%endif%}({% trans 'Enriched' %}) {{video.title}}{% endblock %}

{% block video-element %}
{% if form %}
  {% include 'videos/video-form.html' %}
{% else %}
  {% include 'enrichment/video-element-enrichment.html' %}
{%endif%}
{% endblock video-element %}

{% block more_script %}
{{block.super}}
{% include 'enrichment/video_enrichment-script.html' %}
{% endblock more_script %}