pod/interactive/urls.py
from django.conf.urls import url
from .views import edit_interactive, group_interactive, video_interactive

app_name = "interactive"

urlpatterns = [
    url(
        r"^edit/(?P<slug>[\-\d\w]+)/$",
        edit_interactive,
        name="edit_interactive",
    ),
    url(
        r"^group/(?P<slug>[\-\d\w]+)/$",
        group_interactive,
        name="group_interactive",
    ),
    url(
        r"^video/(?P<slug>[\-\d\w]+)/$",
        video_interactive,
        name="video_interactive",
    ),
    url(
        r"^video/(?P<slug>[\-\d\w]+)/(?P<slug_private>[\-\d\w]+)/$",
        video_interactive,
        name="video_interactive_private",
    ),
]

pod/urls.py
"""Esup-pod URL configuration."""

from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.i18n import JavaScriptCatalog
from django.utils.translation import ugettext_lazy as _

from pod.authentication.views import authentication_login
from pod.authentication.views import authentication_logout
from pod.authentication.views import authentication_login_gateway
from pod.authentication.views import userpicture

from pod.video.views import video
from pod.video.views import video_edit
from pod.video.views import video_add
from pod.video.views import video_delete

# from pod.video.views import video_collaborate
from pod.video.views import channel
from pod.video.views import videos
from pod.video.views import my_videos
from pod.video.views import my_channels
from pod.video.views import channel_edit
from pod.video.views import theme_edit
from pod.video.views import video_notes
from pod.video.views import video_xhr
from pod.video.views import video_count, video_version
from pod.video.views import video_oembed
from pod.video.views import stats_view
from pod.video.views import get_comments, get_children_comment
from pod.video.views import add_comment, delete_comment
from pod.video.views import vote_get, vote_post
from pod.video.views import get_categories, add_category
from pod.video.views import edit_category, delete_category
from pod.video.views import update_video_owner, filter_owners, filter_videos
from pod.video.feeds import RssSiteVideosFeed, RssSiteAudiosFeed
from pod.main.views import (
    contact_us,
    download_file,
    user_autocomplete,
    maintenance,
    robots_txt,
)
from pod.main.rest_router import urlpatterns as rest_urlpatterns
from pod.video_search.views import search_videos
from pod.recorder.views import (
    add_recording,
    recorder_notify,
    claim_record,
    delete_record,
)
# from pod.lti.views import LTIAssignmentAddVideoView, LTIAssignmentGetVideoView
from pod.video.views import PodChunkedUploadView, PodChunkedUploadCompleteView


USE_CAS = getattr(settings, "USE_CAS", False)
USE_SHIB = getattr(settings, "USE_SHIB", False)
USE_OIDC = getattr(settings, "USE_OIDC", False)
OEMBED = getattr(settings, "OEMBED", False)
USE_BBB = getattr(settings, "USE_BBB", False)

if USE_CAS:
    from cas import views as cas_views


urlpatterns = [
    url("select2/", include("django_select2.urls")),
    url("robots.txt", robots_txt),
    url(r'^admin/', admin.site.urls),

    # Translation
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    # App video
    url(r"^videos/$", videos, name="videos"),
    url(r"^rss-video/$", RssSiteVideosFeed(), name="rss-video"),
    url(r"^rss-audio/$", RssSiteAudiosFeed(), name="rss-audio"),
    url(
        r"^rss-video/(?P<slug_c>[\-\d\w]+)/$",
        RssSiteVideosFeed(),
        name="rss-video",
    ),
    url(
        r"^rss-audio/(?P<slug_c>[\-\d\w]+)/$",
        RssSiteAudiosFeed(),
        name="rss-audio",
    ),
    url(
        r"^rss-video/(?P<slug_c>[\-\d\w]+)/(?P<slug_t>[\-\d\w]+)/$",
        RssSiteVideosFeed(),
        name="rss-video",
    ),
    url(
        r"^rss-audio/(?P<slug_c>[\-\d\w]+)/(?P<slug_t>[\-\d\w]+)/$",
        RssSiteAudiosFeed(),
        name="rss-audio",
    ),
    # Manage video owner
    url(
        r"^video/updateowner/put/(?P<user_id>[\d]+)/$",
        update_video_owner,
        name="update_video_owner",
    ),
    url(r"^video/updateowner/owners/$", filter_owners, name="filter_owners"),
    url(
        r"^video/updateowner/videos/(?P<user_id>[\d]+)/$",
        filter_videos,
        name="filter_videos",
    ),
    url(r"^video/(?P<slug>[\-\d\w]+)/$", video, name="video"),
    url(
        r"^video/(?P<slug>[\-\d\w]+)/(?P<slug_private>[\-\d\w]+)/$",
        video,
        name="video_private",
    ),
    url(r"^video_add/$", video_add, name="video_add"),
    url(r"^video_edit/$", video_edit, name="video_edit"),
    url(r"^video_edit/(?P<slug>[\-\d\w]+)/$", video_edit, name="video_edit"),
    url(
        r"^video_delete/(?P<slug>[\-\d\w]+)/$",
        video_delete,
        name="video_delete",
    ),
    url(r"^video_notes/(?P<slug>[\-\d\w]+)/$", video_notes, name="video_notes"),
    url(r"^video_count/(?P<id>[\d]+)/$", video_count, name="video_count"),
    url(r"^video_version/(?P<id>[\d]+)/$", video_version, name="video_version"),
    # url(r'^video_collaborate/(?P<slug>[\-\d\w]+)/$',
    #    video_collaborate,
    #    name='video_collaborate'),
    url(r"^video_xhr/(?P<slug>[\-\d\w]+)/$", video_xhr, name="video_xhr"),
    url(
        r"^video_xhr/(?P<slug>[\-\d\w]+)/(?P<slug_private>[\-\d\w]+)/$",
        video_xhr,
        name="video_xhr",
    ),
    url(
        "api/chunked_upload_complete/",
        PodChunkedUploadCompleteView.as_view(),
        name="api_chunked_upload_complete",
    ),
    url(
        "api/chunked_upload/",
        PodChunkedUploadView.as_view(),
        name="api_chunked_upload",
    ),
    url(r"^ajax_calls/search_user/", user_autocomplete),
    # my channels
    url(r"^my_channels/$", my_channels, name="my_channels"),
    url(
        r"^channel_edit/(?P<slug>[\-\d\w]+)/$",
        channel_edit,
        name="channel_edit",
    ),
    url(r"^theme_edit/(?P<slug>[\-\d\w]+)/$", theme_edit, name="theme_edit"),
    # my videos
    url(r"^my_videos/$", my_videos, name="my_videos"),
    # recording
    url(r"^add_recording/$", add_recording, name="add_recording"),
    url(r"^recorder_notify/$", recorder_notify, name="recorder_notify"),
    url(r"^claim_record/$", claim_record, name="claim_record"),
    url(r"^delete_record/(?P<id>[\d]+)/$", delete_record, name="delete_record"),
    url(r"^search/$", search_videos, name="search_videos"),
    # auth cas
    url(
        r"^authentication_login/$",
        authentication_login,
        name="authentication_login",
    ),
    url(
        r"^authentication_logout/$",
        authentication_logout,
        name="authentication_logout",
    ),
    url(r"^authentication_login/$", authentication_login, name="login"),
    url(r"^authentication_logout/$", authentication_logout, name="logout"),
    url(
        r"^authentication_login_gateway/$",
        authentication_login_gateway,
        name="authentication_login_gateway",
    ),
    url(
        r"^accounts/login/$",
        auth_views.LoginView.as_view(),
        {"redirect_authenticated_user": True},
        name="local-login",
    ),
    url(
        r"^accounts/logout/$",
        auth_views.LogoutView.as_view(),
        {"next_page": "/"},
        name="local-logout",
    ),
    url(r"^accounts/change-password/$", auth_views.PasswordChangeView.as_view()),
    url(r"^accounts/reset-password/$", auth_views.PasswordResetView.as_view()),
    url(r"^accounts/userpicture/$", userpicture, name="userpicture"),
    # rest framework
    url(r"^api-auth/", include("rest_framework.urls")),
    url(r"^rest/", include(rest_urlpatterns)),
    # contact_us
    url(r'^contact_us/$', contact_us, name='contact_us'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^download/$', download_file, name='download_file'),


    # custom
    url(r"^custom/", include("pod.custom.urls")),
]
urlpatterns += (url(r"^maintenance/$", maintenance, name="maintenance"),)

# CAS
if USE_CAS:
    # urlpatterns += [url(r'^sso-cas/', include('cas.urls')), ]
    urlpatterns += [
        url(r"^sso-cas/login/$", cas_views.login, name="cas-login"),
        url(r"^sso-cas/logout/$", cas_views.logout, name="cas-logout"),
    ]

# OIDC
if USE_OIDC:
    urlpatterns += [
        url(r"^oidc/", include("mozilla_django_oidc.urls")),
    ]

# BBB
if USE_BBB:
    urlpatterns += [
        url(r"^bbb/", include("pod.bbb.urls")),
    ]

##
# OEMBED feature patterns
#
if OEMBED:
    urlpatterns += [
        url(r"^oembed/", video_oembed, name="video_oembed"),
    ]

if getattr(settings, "USE_OPENCAST_STUDIO", False):
    urlpatterns += [
        url(r"^studio/", include("pod.recorder.studio_urls")),
    ]

# APPS -> to change !
urlpatterns += [
    url(r"^", include("pod.completion.urls")),
]
urlpatterns += [
    url(r"^", include("pod.chapter.urls")),
]
urlpatterns += [
    url(r"^", include("pod.playlist.urls")),
]

if getattr(settings, "USE_PODFILE", False):
    urlpatterns += [
        url(r"^podfile/", include("pod.podfile.urls")),
    ]

for apps in settings.THIRD_PARTY_APPS:
    urlpatterns += [
        url(r"^" + apps + "/", include("pod.%s.urls" % apps)),
    ]

##
# LTI feature patterns
#
# if getattr(settings, 'LTI_ENABLED', False):
#    # LTI href
#    urlpatterns += [
#        url(r'^lti/', include('lti_provider.urls')),
#        url(r'^assignment/addvideo/',
#            LTIAssignmentAddVideoView.as_view()),
#        url(r'^assignment/getvideo/',
#            LTIAssignmentGetVideoView.as_view()),
#    ]
##
# H5P feature patterns
#
if getattr(settings, "H5P_ENABLED", False):
    urlpatterns += [
        url(r"^h5p/login/", authentication_login, name="h5p_login"),
        url(r"^h5p/logout/", authentication_logout, name="h5p_logout"),
        url(r"^h5p/", include("h5pp.urls")),
    ]

if getattr(settings, "USE_STATS_VIEW", False):
    urlpatterns += [
        url(r"^video_stats_view/$", stats_view, name="video_stats_view"),
        url(
            r"^video_stats_view/(?P<slug>[-\w]+)/$",
            stats_view,
            name="video_stats_view",
        ),
        url(
            r"^video_stats_view/(?P<slug>[-\w]+)/(?P<slug_t>[-\w]+)/$",
            stats_view,

pod/main/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.contrib.flatpages.models import FlatPage
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.template.defaultfilters import slugify
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import connection
import os
import mimetypes

FILES_DIR = getattr(settings, "FILES_DIR", "files")


def get_nextautoincrement(model):
    cursor = connection.cursor()
    cursor.execute(
        "SELECT Auto_increment FROM information_schema.tables "
        + 'WHERE table_name="{0}" AND table_schema=DATABASE();'.format(
            model._meta.db_table
        )
    )
    row = cursor.fetchone()
    cursor.close()
    return row[0]


def get_upload_path_files(instance, filename):
    fname, dot, extension = filename.rpartition(".")
    try:
        fname.index("/")
        return os.path.join(
            FILES_DIR,
            "%s/%s.%s"
            % (
                os.path.dirname(fname),
                slugify(os.path.basename(fname)),
                extension,
            ),
        )
    except ValueError:
        return os.path.join(FILES_DIR, "%s.%s" % (slugify(fname), extension))


class CustomImageModel(models.Model):
    file = models.ImageField(
        _("Image"),
        null=True,
        upload_to=get_upload_path_files,
        blank=True,
        max_length=255,
    )

    @property
    def file_type(self):
        filetype = mimetypes.guess_type(self.file.path)[0]
        if filetype is None:
            fname, dot, extension = self.file.path.rpartition(".")
            filetype = extension.lower()
        return filetype

    file_type.fget.short_description = _("Get the file type")

    @property
    def file_size(self):
        return os.path.getsize(self.file.path)

    file_size.fget.short_description = _("Get the file size")

    @property
    def name(self):
        return os.path.basename(self.file.path)

    name.fget.short_description = _("Get the file name")

    def file_exist(self):
        return self.file and os.path.isfile(self.file.path)

    def __str__(self):
        return "%s (%s, %s)" % (self.name, self.file_type, self.file_size)


class CustomFileModel(models.Model):
    file = models.ImageField(
        _("Image"),
        null=True,
        upload_to=get_upload_path_files,
        blank=True,
        max_length=255,
    )

    @property
    def file_type(self):
        filetype = mimetypes.guess_type(self.file.path)[0]
        if filetype is None:
            fname, dot, extension = self.file.path.rpartition(".")
            filetype = extension.lower()
        return filetype

    file_type.fget.short_description = _("Get the file type")

    @property
    def file_size(self):
        return os.path.getsize(self.file.path)

    file_size.fget.short_description = _("Get the file size")

    @property
    def name(self):
        return os.path.basename(self.file.path)

    name.fget.short_description = _("Get the file name")

    def file_exist(self):
        return self.file and os.path.isfile(self.file.path)

    def __str__(self):
        return "%s (%s, %s)" % (self.name, self.file_type, self.file_size)


class LinkFooter(models.Model):
    title = models.CharField(_("Title"), max_length=250)
    order = models.PositiveSmallIntegerField(_("order"), default=1, blank=True, null=True)
    url = models.CharField(
        _("Web link"),
        blank=True,
        null=True,
        max_length=250,
        help_text=_("This field allows you to add an url."),
    )
    page = models.ForeignKey(
        FlatPage,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        help_text=_("Select the page of Pod you want to link with."),
    )
    sites = models.ManyToManyField(Site)

    class Meta:
        ordering = ["order", "title"]
        verbose_name = _("bottom menu")
        verbose_name_plural = _("bottom menu")

    def get_url(self):
        if self.url:
            return self.url
        return self.page.url

    def __str__(self):
        return "%s - %s" % (self.id, self.title)

    def clean(self):
        if self.url is None and self.page is None:
            raise ValidationError(_("You must give an URL or a page to link the link"))


@receiver(post_save, sender=LinkFooter)
def default_site_link_footer(sender, instance, created, **kwargs):
    if len(instance.sites.all()) == 0:
        instance.sites.add(Site.objects.get_current())


class Configuration(models.Model):
    key = models.SlugField(
        _("Key"),
        unique=True,
        max_length=100,
        help_text=_("Key of the configuration"),
        editable=False,
    )
    value = models.CharField(
        _("Value"), max_length=255, help_text=_("Value of the configuration")
    )
    description = models.CharField(
        _("Description"),
        max_length=255,
        help_text=_("Description of the configuration"),
        editable=False,
    )


class AdditionalChannelTab(models.Model):
    name = models.CharField(_("Value"), max_length=40, help_text=_("Name of the tab"))

    def __str__(self):
        return "%s" % (self.name)

    class Meta:
        verbose_name = _("Additional channels Tab")
        verbose_name_plural = _("Additional channel Tabs")

pod/interactive/forms.py
from django import forms
from django.contrib.admin import widgets
from django.utils.translation import ugettext_lazy as _
from .models import InteractiveGroup
from django.contrib.auth.models import Group


class InteractiveGroupForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(InteractiveGroupForm, self).__init__(*args, **kwargs)
        self.fields["groups"].widget = widgets.FilteredSelectMultiple(
            _("Groups"), False, attrs={}
        )
        self.fields["groups"].queryset = Group.objects.all()

    class Meta(object):
        model = InteractiveGroup
        fields = ("groups",)  # '__all__'

pod/interactive/templates/interactive/edit_interactive.html
{% extends 'videos/video.html' %}
{% load i18n %}
{% load static %}

{% block page_title %}{% trans 'Interactive of the video' %} "{{video.title}}" {% endblock page_title %}

{% block page_extra_head %}
<style>
  div.pod-inner {
    min-height: 56rem;
    height:100%;
  }
  #collapseAside {
    max-height: 60rem;
    overflow-y: auto;
  }
  .loader {
    border: 5px solid #f3f3f3;
    border-top: 5px solid #3498db;
    border-radius: 50%;
    width: 50px;
    height: 50px;
    animation: spin 2s linear infinite;
    margin: auto;
  }
  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
</style>

{% endblock page_extra_head %}

{% block video-element %}

<div id="load-message" align="center">
  {% trans 'Loading, please wait...' %}
</div>
<div class="loader"></div>
<div id="configuration" style="display:none;">
    <h3 itemprop="name" >
      {{video.title}}
      <small>
      {% if video.interactive.is_interactive %}
        {% if request.user == video.owner or request.user.is_superuser %}
        <!--
        <button type="submit" class="btn btn-primary btn-sm" id="button_delete_video" title="{% trans 'Delete the interactive part of this video' %}">
          <i data-feather="x-circle"></i>
          <span class="sr-only">{% trans 'Delete the interactive part of this video' %}</span>
        </button>
        -->
        <form action="{% url 'h5pp:h5plistContents' %}?contentId={{interactive.h5p.content_id}}" id="button_delete_video" style="display:inline-block;">
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary btn-sm" title="{% trans 'Back' %}">
            <i class="bi bi-x-circle"></i>
            <span class="visually-hidden">{% trans 'Back' %}</span>
          </button>
        </form>
        <button type="submit" class="btn btn-primary btn-sm" id="button_manage" title="{% trans 'Manage scores' %}">
          <i class="bi bi-card-list"></i>
          <span class="visually-hidden">{% trans 'Manage scores' %}</span>
        </button>
        {% endif %}
      {% endif %}
        <form action="{% url 'video' slug=video.slug %}" id="video_back" style="display:inline-block;">
          <button type="submit" class="btn btn-secondary btn-sm" id="button_video_back" title="{% trans 'Back' %}">
            <i class="bi bi-arrow-left-circle"></i>
            <span class="visually-hidden">{% trans 'Back' %}</span>
          </button>
        </form>
      </small>
    </h3>
</div>

{% if not request.GET.is_iframe%}
<p class="save-button" align="center" style="display:none;">
  <button type="submit" class="btn btn-primary btn-sm button_savecontinue_interactive">
    <span id="save" class="glyphicon glyphicon-check"></span>
    {% trans 'Save and continue' %}
  </button>
  <button type="submit" class="btn btn-primary btn-sm button_savequit_interactive">
    <span id="save" class="glyphicon glyphicon-new-window"></span>
    {% trans 'Save and see the interactive video' %}
  </button>
</p>
{% endif %}

{% if video.interactive.is_interactive == True %}
  <iframe id="ieditor" src="{% url "h5pp:h5pedit" contentId=interactive.h5p.content_id %}?title={{video.title}}&is_iframe=true" style="display:none; overflow: auto;min-height: 70%;" width="100%" frameBorder="0" loading="lazy"></iframe><!-- height=985px-->
{% else %}
  <iframe id="ieditor" src="{% url 'h5pp:h5pcreate' %}?h5p_library={{interactive.version.machine_name}} {{interactive.version.major_version}}.{{interactive.version.minor_version}}&title={{video.title}}&is_iframe=true" style="display:none; overflow: auto; min-height: 70%;" width="100%" frameBorder="0" loading="lazy"></iframe>
{% endif %}

{% if not request.GET.is_iframe%}
<div class="save-button" align="center" style="display:none;">
  <button type="submit" class="btn btn-primary button_savecontinue_interactive" title="{% trans 'Save and continue' %}">
    <span id="save" class="glyphicon glyphicon-check"></span>
    {% trans 'Save and continue' %}
  </button>
  <button type="submit" class="btn btn-primary button_savequit_interactive" title="{% trans 'Save and return to video' %}">
    <span id="save" class="glyphicon glyphicon-new-window"></span>
    {% trans 'Save and see the interactive video' %}
  </button>
</div>
{% endif %}

{% endblock video-element %}


{% block page_aside %}
  <div class="card card-body p-2 p-md-3" id="card-interactiveeditinformations">
    <h5 class="card-title ps-2">
      <i class="bi bi-info-circle"></i>&nbsp;{% trans 'Informations' %}
    </h5>
    <div class="card-text small">
      {% if video.owner == request.user or request.user.is_superuser %}
      <p><a href="{% url 'interactive:group_interactive' slug=video.slug %}" title="{% trans 'You can specify the group(s) of users who can access this page' %}"><i class="bi bi-people"></i>&nbsp;{% trans 'You can specify the group(s) of users who can access this page' %}</a></p>
      {% endif %}
      <p class="text-info">
        {% trans 'Do not forget to save your work regularly. Especially if you add an interaction.' %}
        <br>
        {% trans "To save and continue your work click on the button [Save and continue]. If you have completed your work click on the button [Save and see the interactive video] to view your new interactive video." %}
      </p>
    </div>
  </div>
  {% if video.owner == request.user or request.user.is_superuser or request.user in video.additional_owners.all %}
  <div class="card" id="card-managevideo">
  <h2 class="card-header card-title ps-2 h4"><i class="bi bi-gear"></i>&nbsp;{% trans "Manage video"%}</h2>
      <div class="card-body card-text text-center">
      {% include "videos/link_video.html" %}
      </div>
  </div>
  {% endif %}

{% endblock page_aside %}

{% block more_script %}
<script>
  var editorReady = false;
  var continueClick = false;
  var quitClick = false;
  function chargementEditeur(){
    //lancement interface editeur quand ce dernier est fini de charger
    if( $('#ieditor').contents().find('.h5p-editor-iframe').length > 0 &&
      $('#ieditor').contents().find('.h5p-editor-iframe').contents().find('.h5p-add-file').length > 0 && editorReady == false)
    {
      editor();
      $('#ieditor').get(0).contentWindow.ns.$('.h5p-chooser.h5p-quality.h5p-show li').first().click()
      $('#load-message').hide();
      $('.loader').hide();
      $("#ieditor").fadeIn('slow');
      $('.save-button').show();
      $('#configuration').show();
    } else {
      setTimeout(chargementEditeur,2000); /* rappel après 2 secondes = 2000 millisecondes */
    }
  }
  {% if video.is_video %}
  /** get all mp4 format **/
  var mp4_sources = {{video.get_video_mp4_json|safe}};
  {% else %}
  {% if video.get_video_m4a %}
  var mp4_sources = [{
    src: '{{video.get_video_m4a.source_file.url}}',
    type: '{{video.get_video_m4a.encoding_format}}',
  }];
  {% endif %}
  {% endif %}

  function editor() {
    editorReady = true;
    $('#ieditor').get(0).contentWindow.ns.$('select[name="h5peditor-library"]').hide();
    $('#ieditor').get(0).contentWindow.ns.$('.h5p-more-libraries').hide();

    {% if not interactive.h5p %}
    for(i=0;i<mp4_sources.length;i++){
      //console.log(mp4_sources[i].src);
      $('#ieditor').get(0).contentWindow.ns.$('.h5p-file-url.h5peditor-text').val('{% if request.is_secure %}https{% else %}http{% endif %}://{{ request.META.HTTP_HOST }}'+mp4_sources[i].src);
      $('#ieditor').get(0).contentWindow.ns.$('.h5peditor-button-textual.h5p-insert').click();
    }
    {% endif %}

    $('#ieditor').get(0).contentWindow.ns.$('.h5peditor-tab-a.h5peditor-tab-assets').click();
    $('#ieditor').get(0).contentWindow.ns.$('.h5peditor-tab-li:first').hide();
    $('#ieditor').fadeIn('slow');
    $('#button_save_interactive').show();
    $('.alert').hide();
  }


    $('#configuration').hide();
    $('#info').hide();
    // Save and continue editing
    $('.button_savecontinue_interactive').on('click', function(){
      continueClick = true;
      $('#load-message').show();
      $('.loader').show();
      $('#info').hide();
      $('#configuration').hide();
      $('.save-button').hide();
      $("#ieditor").hide();
      $('#ieditor').contents().find('#submit_editor').click();
    });
    // Save and return to video page
    $('.button_savequit_interactive').on('click', function() {
      quitClick = true;
      $('#load-message').show();
      $('.loader').show();
      $('#info').hide();
      $('#configuration').hide();
      $('.save-button').hide();
      $('#ieditor').hide();
      $('#ieditor').contents().find('#submit_editor').click();
    });
    //Delete interactive video
    $('#button_delete_video').on('submit', function() {
      var data_form = $( this ).serializeArray();
      $.ajax({
        url: '{% url 'h5pp:h5plistContents' %}?contentId={{interactive.h5p.content_id}}',
        data:data_form,
        type: 'POST',
        success: function() {
          window.location.assign("{% url 'video' slug=video.slug %}");
        }
      });
      return false;
    });

    //Go to H5PP plugin management
    {% if interactive.h5p %}
    $('#button_manage').on('click', function() {
      window.location.assign("{% url 'h5pp:h5pscore' contentId=interactive.h5p.content_id %}" );
    });
    {% endif %}

    chargementEditeur();

    $('#ieditor').on('load', function() {

      if(continueClick == true) {
        window.location.assign(window.location.href);
      }
      if(quitClick == true) {
        window.location.assign("{% url 'interactive:video_interactive' slug=video.slug %}");
      }
      $('#ieditor').contents().find('#id_title').hide();
      $('#ieditor').contents().find('.label_form').hide();
      $('#ieditor').contents().find('#id_h5p_type').hide();
      $('#ieditor').contents().find('#submit_editor').hide();
    });

</script>
{% endblock more_script %}

pod/interactive/templates/interactive/video_interactive-iframe.html
{% extends 'videos/video-iframe.html' %}
{% load i18n %}
{% load static %}

{% block page_extra_head %}
<style>
#h5pcontent {
    margin: auto;
    text-align: center;
    background-color: black;
    width: 100%;
    height: 480px;
}
#icontent {
    display: block;
    margin: 0 auto;
    width: 100%;
    height: 100%;
    background-color: black;
}
</style>
{% endblock page_extra_head %}

{% block page_title %}{%if channel %}{{channel.title}} - {%endif%}{%if theme %}{{theme.title}} - {%endif%}({% trans 'Interactive video' %}) {{video.title}}{% endblock %}

{% block video-element %}
{% if form %}
{% include 'videos/video-form.html' %}
{% else %}
<div id="h5pcontent">
    <iframe id="icontent" src="{% url 'h5pp:h5pcontent' %}?contentId={{more_data.h5p.content_id}}&is_iframe=true" style="display:none;" frameBorder="0" allowfullscreen="allowfullscreen" scrolling="no" loading="lazy"></iframe>
</div>
<form method="post" action="{% url 'video_count' id=video.id %}" id="video_count_form">
{% csrf_token %}
</form>
{% endif %}
{% endblock video-element %}


{% block more_script %}
{{block.super}}
<script>
    var video_height = 0;
    $('#icontent').on('load',function() {
        $('#icontent').fadeIn('slow', function(){
            video_height = $('#icontent').contents().find("#h5p-iframe-{{more_data.h5p.content_id}}").height();
            $("#h5pcontent").height(video_height);
        });
        $('#icontent').contents().find("body").attr("style", "background-color:black");
    });

</script>
{% endblock more_script %}